version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL: postgres://postgres:postgres@database:5432/mydb
      - NODE_ENV: development
      - ports: 3001
    volumes:
      - ./backend:/usr/src/app/
      - ./usr/src/app/node_modules
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  database:
    build:
      context: ./database/Dockerfile
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:  

networks:
  app-network:
    driver: bridge
